apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  labels:
    {{- include "jobros.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.jwtSecret | b64enc }}
